let newset = new Set()
newset.add(1)
newset.add(2)
newset.add(3)
newset.add(4)
console.log(newset)

console.log(newset.has(3))
console.log(newset.delete(2))
console.log(newset)
console.log(newset.size)
newset.clear()
console.log("newset : ",newset)
console.log(newset.size)